name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: mkdir build
      run: mkdir build && cd build
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: echo 
      run: ok
